version: "3.8"

services:
  nm-computercare-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: leonard1thecoder/nm-computercare-backend:latest
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      SPRING_REDIS_HOST: ${REDIS_HOST:-redis}
      SPRING_REDIS_PORT: ${REDIS_PORT:-6379}
      SUPABASE_URL: ${SUPABASE_URL}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      PORT: ${CONTAINER_PORT:-9098}
    ports:
      - "${APP_EXTERNAL_PORT:-8080}:${CONTAINER_PORT:-9098}"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
      start_interval: 5s

  nextjs:
    image: leonard1thecoder/nextjs-bun-app:latest
    container_name: nextjs-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network
    environment:
      # If you want frontend to call backend directly (CORS bean required in Spring Boot)
      #API_URL: http://localhost:8080
      # If you prefer internal Docker DNS (no CORS needed, Next.js rewrites /api)
       API_URL: http://nm-computercare-backend:9098

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
